# Generated by Django 4.1.7 on 2023-03-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_Birth', models.DateField()),
                ('Website', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=15)),
                ('City', models.CharField(max_length=254)),
                ('Degree', models.CharField(max_length=254)),
                ('Email', models.EmailField(max_length=254)),
                ('Freelance', models.CharField(choices=[('A', 'Available'), ('NA', 'Non Available')], max_length=3)),
            ],
        ),
    ]
