# Generated by Django 4.1.7 on 2023-03-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='personaldetails',
            new_name='personaldetailsModels',
        ),
    ]
