# Generated by Django 4.1.7 on 2023-03-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0002_rename_personaldetails_personaldetailsmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetailsmodels',
            name='Phone',
        ),
        migrations.AddField(
            model_name='personaldetailsmodels',
            name='FName',
            field=models.CharField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='personaldetailsmodels',
            name='PhoneNumber',
            field=models.CharField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='personaldetailsmodels',
            name='City',
            field=models.CharField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetailsmodels',
            name='Date_of_Birth',
            field=models.DateField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='personaldetailsmodels',
            name='Degree',
            field=models.CharField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetailsmodels',
            name='Email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetailsmodels',
            name='Freelance',
            field=models.CharField(choices=[('A', 'Available'), ('NA', 'Non Available')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetailsmodels',
            name='Website',
            field=models.CharField(default=None, max_length=254, null=True),
        ),
        migrations.AlterModelTable(
            name='personaldetailsmodels',
            table='PersonaldetailsModels',
        ),
    ]
