# Generated by Django 4.1.7 on 2023-03-14 04:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0003_remove_personaldetailsmodels_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaldetailsmodels',
            options={'ordering': ['FName', 'City']},
        ),
        migrations.AlterField(
            model_name='personaldetailsmodels',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='personaldetailsmodels',
            table=None,
        ),
    ]
