# Generated by Django 4.1.7 on 2023-03-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0005_alter_personaldetailsmodels_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetailsmodels',
            name='id',
            field=models.AutoField(help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='personaldetailsmodels',
            table='personaldetailsmodels',
        ),
    ]
