# Generated by Django 4.1.7 on 2023-03-19 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0007_skilsmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillsmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default=None, max_length=254)),
                ('skillPerc', models.IntegerField()),
                ('skill2', models.CharField(default=None, max_length=254)),
                ('skill2Perc', models.IntegerField()),
                ('skill3', models.CharField(default=None, max_length=254)),
                ('skill3Perc', models.IntegerField()),
                ('skill4', models.CharField(default=None, max_length=254)),
                ('skill4Perc', models.IntegerField()),
                ('skill5', models.CharField(default=None, max_length=254)),
                ('skill5Perc', models.IntegerField()),
                ('skill6', models.CharField(default=None, max_length=254)),
                ('skill6Perc', models.IntegerField()),
                ('skill_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPAResume.personaldetailsmodels')),
            ],
        ),
        migrations.DeleteModel(
            name='skilsmodels',
        ),
    ]
