# Generated by Django 4.1.7 on 2023-03-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0008_skillsmodels_delete_skilsmodels'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personaldetailsmodels',
            table='personaldetail',
        ),
    ]
