# Generated by Django 4.1.7 on 2023-03-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0009_alter_personaldetailsmodels_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skillsmodels',
            table='Skills',
        ),
    ]
