# Generated by Django 4.1.7 on 2023-03-20 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0010_alter_skillsmodels_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsmodels',
            name='id',
            field=models.AutoField(help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Educationmodels',
            fields=[
                ('id', models.AutoField(help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('courses_Name', models.CharField(default=None, max_length=254)),
                ('percentage', models.CharField(default=None, max_length=254)),
                ('duration', models.CharField(default=None, max_length=254)),
                ('institute_Name', models.CharField(default=None, max_length=254)),
                ('comments', models.CharField(default=None, max_length=254)),
                ('Education_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPAResume.personaldetailsmodels')),
            ],
            options={
                'db_table': 'Education',
            },
        ),
    ]
