# Generated by Django 4.1.7 on 2023-03-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0011_alter_skillsmodels_id_educationmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetailsmodels',
            name='Address',
            field=models.CharField(default=None, max_length=254, null=True),
        ),
    ]
