# Generated by Django 4.1.7 on 2023-03-20 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0012_personaldetailsmodels_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('TECHNICAL', models.CharField(choices=[('T', 'TECHNICAL'), ('NT', 'Non TECHNICAL')], default=None, max_length=2, null=True)),
                ('Certification_Name', models.CharField(default=None, max_length=254)),
                ('Certification_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPAResume.personaldetailsmodels')),
            ],
            options={
                'db_table': 'Certification',
            },
        ),
    ]
