# Generated by Django 4.1.7 on 2023-03-20 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0013_certification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certification',
            new_name='CertificationModel',
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.AutoField(help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('Company_Name', models.CharField(default=None, max_length=254)),
                ('Designation', models.CharField(default=None, max_length=254)),
                ('Duration', models.CharField(default=None, max_length=254)),
                ('Command1', models.CharField(default=None, max_length=254)),
                ('Command2', models.CharField(default=None, max_length=254)),
                ('Command3', models.CharField(default=None, max_length=254)),
                ('Command4', models.CharField(default=None, max_length=254)),
                ('Experience_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPAResume.personaldetailsmodels')),
            ],
            options={
                'db_table': 'Experience',
            },
        ),
    ]
