# Generated by Django 4.1.7 on 2023-03-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0014_rename_certification_certificationmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Educationmodels',
            new_name='EducationModel',
        ),
        migrations.RenameModel(
            old_name='Skillsmodels',
            new_name='SkillsModel',
        ),
    ]
