# Generated by Django 4.1.7 on 2023-03-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0015_rename_educationmodels_educationmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetailsmodels',
            name='Imagepath',
            field=models.CharField(default=None, max_length=254, null=True),
        ),
    ]
