# Generated by Django 4.1.7 on 2023-03-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0016_personaldetailsmodels_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationmodel',
            name='id',
            field=models.AutoField(auto_created=True, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='id',
            field=models.AutoField(auto_created=True, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='id',
            field=models.AutoField(auto_created=True, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetailsmodels',
            name='id',
            field=models.AutoField(auto_created=True, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skillsmodel',
            name='id',
            field=models.AutoField(auto_created=True, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
