# Generated by Django 4.1.7 on 2023-04-13 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0017_alter_certificationmodel_id_alter_educationmodel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('twitter', models.URLField(default=None, max_length=254)),
                ('Facebook', models.URLField(default=None, max_length=254)),
                ('instagram', models.URLField(default=None, max_length=254)),
                ('skype', models.URLField(default=None, max_length=254)),
                ('linkedin', models.URLField(default=None, max_length=254)),
                ('SocialMedia_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPAResume.personaldetailsmodels')),
            ],
            options={
                'db_table': 'SocialMedia',
            },
        ),
    ]
