# Generated by Django 4.1.7 on 2023-04-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0018_socialmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmodel',
            name='Facebook',
            field=models.CharField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='socialmodel',
            name='instagram',
            field=models.CharField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='socialmodel',
            name='linkedin',
            field=models.CharField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='socialmodel',
            name='skype',
            field=models.CharField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='socialmodel',
            name='twitter',
            field=models.CharField(default=None, max_length=254),
        ),
    ]
