# Generated by Django 4.1.7 on 2023-04-13 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0020_alter_socialmodel_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('Command', models.CharField(default=None, max_length=254)),
                ('Command1', models.CharField(default=None, max_length=254)),
                ('Pic', models.URLField(default=None, max_length=254)),
                ('Name', models.CharField(default=None, max_length=254)),
                ('Designation', models.CharField(default=None, max_length=254)),
                ('Testimonials_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPAResume.personaldetailsmodels')),
            ],
            options={
                'db_table': 'Testimonials',
            },
        ),
    ]
