# Generated by Django 4.1.7 on 2023-04-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0021_testimonialsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetailsmodels',
            name='Location',
            field=models.URLField(default=None, max_length=254, null=True),
        ),
    ]
