# Generated by Django 4.1.7 on 2023-04-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0023_alter_personaldetailsmodels_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetailsmodels',
            name='BGImage',
            field=models.URLField(default=None, null=True),
        ),
    ]
