# Generated by Django 4.1.7 on 2023-04-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0024_personaldetailsmodels_bgimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='knowledgeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('knowledge', models.CharField(default=None, max_length=254)),
                ('knowledgeModel_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPAResume.personaldetailsmodels')),
            ],
            options={
                'db_table': 'knowledge',
            },
        ),
    ]
