# Generated by Django 4.1.7 on 2023-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0025_knowledgemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetailsmodels',
            name='Domain',
            field=models.CharField(default=None, max_length=254, null=True),
        ),
    ]
