# Generated by Django 4.1.7 on 2023-04-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0027_projectsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='Filter',
            field=models.CharField(default=None, max_length=254),
        ),
    ]
