# Generated by Django 4.1.7 on 2023-04-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0028_projectsmodel_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsmodel',
            old_name='Filter',
            new_name='Filters',
        ),
    ]
