# Generated by Django 4.1.7 on 2023-04-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0030_rename_filters_projectsmodel_projectskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('comments1', models.CharField(default=None, max_length=254, null=True)),
                ('comments2', models.CharField(default=None, max_length=254, null=True)),
                ('comments3', models.CharField(default=None, max_length=254, null=True)),
                ('comments4', models.CharField(default=None, max_length=254, null=True)),
                ('comments5', models.CharField(default=None, max_length=254, null=True)),
                ('comments6', models.CharField(default=None, max_length=254, null=True)),
                ('comments7', models.CharField(default=None, max_length=254, null=True)),
                ('comments8', models.CharField(default=None, max_length=254, null=True)),
                ('comments9', models.CharField(default=None, max_length=254, null=True)),
                ('comments10', models.CharField(default=None, max_length=254, null=True)),
                ('comments_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPAResume.personaldetailsmodels')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
