# Generated by Django 4.1.7 on 2023-04-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0031_commentsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='comments1',
            field=models.CharField(default=None, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='comments10',
            field=models.CharField(default=None, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='comments2',
            field=models.CharField(default=None, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='comments3',
            field=models.CharField(default=None, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='comments4',
            field=models.CharField(default=None, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='comments5',
            field=models.CharField(default=None, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='comments6',
            field=models.CharField(default=None, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='comments7',
            field=models.CharField(default=None, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='comments8',
            field=models.CharField(default=None, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='comments9',
            field=models.CharField(default=None, max_length=99999, null=True),
        ),
    ]
