# Generated by Django 4.1.7 on 2023-04-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0033_projectsmodel_projecttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='ProjectTitle',
            field=models.CharField(default=None, max_length=254, null=True),
        ),
    ]
