# Generated by Django 4.1.7 on 2023-04-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0035_remove_projectsmodel_projecttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='ProjectTitle',
            field=models.CharField(default=None, max_length=254),
        ),
    ]
