# Generated by Django 4.1.7 on 2023-04-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0036_projectsmodel_projecttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='ProjectTitle',
            field=models.CharField(max_length=254),
        ),
    ]
