# Generated by Django 4.1.7 on 2023-12-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0037_alter_projectsmodel_projecttitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gmail',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('Username', models.CharField(default=None, max_length=99999, null=True)),
                ('Password', models.CharField(default=None, max_length=99999, null=True)),
                ('Gmail_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPAResume.personaldetailsmodels')),
            ],
        ),
    ]
