# Generated by Django 4.1.7 on 2023-12-28 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RPAResume", "0039_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="UploadedFile_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="RPAResume.personaldetailsmodels",
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="id",
            field=models.AutoField(
                auto_created=True,
                help_text="Unique ID for this particular book across whole library",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
