# Generated by Django 4.1.7 on 2023-12-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RPAResume", "0040_uploadedfile_uploadedfile_id_alter_uploadedfile_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedfile",
            old_name="UploadedFile_id",
            new_name="File_id",
        ),
    ]
