# Generated by Django 4.1.7 on 2023-12-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RPAResume", "0041_rename_uploadedfile_id_uploadedfile_file_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedfile",
            old_name="File_id",
            new_name="File",
        ),
    ]
