# Generated by Django 4.1.7 on 2023-12-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RPAResume", "0042_rename_file_id_uploadedfile_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedfile",
            old_name="File",
            new_name="File_id",
        ),
    ]
