# Generated by Django 4.1.7 on 2023-12-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RPAResume", "0043_rename_file_uploadedfile_file_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Gmail",
            new_name="GmailModel",
        ),
    ]
